//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kermalis.VGMusicStudio.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kermalis.VGMusicStudio.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 {0} key 的本地化字符串。
        /// </summary>
        internal static string ConfigKeySubkey {
            get {
                return ResourceManager.GetString("ConfigKeySubkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Would you like to stop playing the current playlist? 的本地化字符串。
        /// </summary>
        internal static string EndPlaylistBody {
            get {
                return ResourceManager.GetString("EndPlaylistBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid command in track {0} at 0x{1:X}: 0x{2:X} 的本地化字符串。
        /// </summary>
        internal static string ErrorAlphaDreamDSEMP2KSDATInvalidCommand {
            get {
                return ResourceManager.GetString("ErrorAlphaDreamDSEMP2KSDATInvalidCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot copy invalid game code &quot;{0}&quot; 的本地化字符串。
        /// </summary>
        internal static string ErrorAlphaDreamMP2KCopyInvalidGameCode {
            get {
                return ResourceManager.GetString("ErrorAlphaDreamMP2KCopyInvalidGameCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game code &quot;{0}&quot; is missing. 的本地化字符串。
        /// </summary>
        internal static string ErrorAlphaDreamMP2KMissingGameCode {
            get {
                return ResourceManager.GetString("ErrorAlphaDreamMP2KMissingGameCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error parsing game code &quot;{0}&quot; in &quot;{1}&quot;{2} 的本地化字符串。
        /// </summary>
        internal static string ErrorAlphaDreamMP2KParseGameCode {
            get {
                return ResourceManager.GetString("ErrorAlphaDreamMP2KParseGameCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Playlist &quot;{0}&quot; has song {1} defined more than once between decimal and hexadecimal. 的本地化字符串。
        /// </summary>
        internal static string ErrorAlphaDreamMP2KSongRepeated {
            get {
                return ResourceManager.GetString("ErrorAlphaDreamMP2KSongRepeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;{0}&quot; count must be the same as &quot;{1}&quot; count. 的本地化字符串。
        /// </summary>
        internal static string ErrorAlphaDreamMP2KSongTableCounts {
            get {
                return ResourceManager.GetString("ErrorAlphaDreamMP2KSongTableCounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;{0}&quot; must be True or False. 的本地化字符串。
        /// </summary>
        internal static string ErrorBoolParse {
            get {
                return ResourceManager.GetString("ErrorBoolParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Color {0} has an invalid key. 的本地化字符串。
        /// </summary>
        internal static string ErrorConfigColorInvalidKey {
            get {
                return ResourceManager.GetString("ErrorConfigColorInvalidKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Color {0} is not defined. 的本地化字符串。
        /// </summary>
        internal static string ErrorConfigColorMissing {
            get {
                return ResourceManager.GetString("ErrorConfigColorMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Color {0} is defined more than once between decimal and hexadecimal. 的本地化字符串。
        /// </summary>
        internal static string ErrorConfigColorRepeated {
            get {
                return ResourceManager.GetString("ErrorConfigColorRepeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;{0}&quot; is invalid. 的本地化字符串。
        /// </summary>
        internal static string ErrorConfigKeyInvalid {
            get {
                return ResourceManager.GetString("ErrorConfigKeyInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;{0}&quot; is missing. 的本地化字符串。
        /// </summary>
        internal static string ErrorConfigKeyMissing {
            get {
                return ResourceManager.GetString("ErrorConfigKeyMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;{0}&quot; must have at least one entry. 的本地化字符串。
        /// </summary>
        internal static string ErrorConfigKeyNoEntries {
            get {
                return ResourceManager.GetString("ErrorConfigKeyNoEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown header version: 0x{0:X} 的本地化字符串。
        /// </summary>
        internal static string ErrorDSEInvalidHeaderVersion {
            get {
                return ResourceManager.GetString("ErrorDSEInvalidHeaderVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid key in track {0} at 0x{1:X}: {2} 的本地化字符串。
        /// </summary>
        internal static string ErrorDSEInvalidKey {
            get {
                return ResourceManager.GetString("ErrorDSEInvalidKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There are no &quot;bgm(NNNN).smd&quot; files. 的本地化字符串。
        /// </summary>
        internal static string ErrorDSENoSequences {
            get {
                return ResourceManager.GetString("ErrorDSENoSequences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error Loading Global Config 的本地化字符串。
        /// </summary>
        internal static string ErrorGlobalConfig {
            get {
                return ResourceManager.GetString("ErrorGlobalConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error Loading Song {0} 的本地化字符串。
        /// </summary>
        internal static string ErrorLoadSong {
            get {
                return ResourceManager.GetString("ErrorLoadSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid running status command in track {0} at 0x{1:X}: 0x{2:X} 的本地化字符串。
        /// </summary>
        internal static string ErrorMP2KInvalidRunningStatusCommand {
            get {
                return ResourceManager.GetString("ErrorMP2KInvalidRunningStatusCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Too many nested call events in track {0} 的本地化字符串。
        /// </summary>
        internal static string ErrorMP2KSDATNestedCalls {
            get {
                return ResourceManager.GetString("ErrorMP2KSDATNestedCalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error Loading GBA ROM (AlphaDream) 的本地化字符串。
        /// </summary>
        internal static string ErrorOpenAlphaDream {
            get {
                return ResourceManager.GetString("ErrorOpenAlphaDream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error Loading DSE Folder 的本地化字符串。
        /// </summary>
        internal static string ErrorOpenDSE {
            get {
                return ResourceManager.GetString("ErrorOpenDSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error Loading GBA ROM (MP2K) 的本地化字符串。
        /// </summary>
        internal static string ErrorOpenMP2K {
            get {
                return ResourceManager.GetString("ErrorOpenMP2K", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error Loading SDAT File 的本地化字符串。
        /// </summary>
        internal static string ErrorOpenSDAT {
            get {
                return ResourceManager.GetString("ErrorOpenSDAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error parsing &quot;{0}&quot;{1} 的本地化字符串。
        /// </summary>
        internal static string ErrorParseConfig {
            get {
                return ResourceManager.GetString("ErrorParseConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error Exporting DLS 的本地化字符串。
        /// </summary>
        internal static string ErrorSaveDLS {
            get {
                return ResourceManager.GetString("ErrorSaveDLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error Exporting MIDI 的本地化字符串。
        /// </summary>
        internal static string ErrorSaveMIDI {
            get {
                return ResourceManager.GetString("ErrorSaveMIDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error Exporting SF2 的本地化字符串。
        /// </summary>
        internal static string ErrorSaveSF2 {
            get {
                return ResourceManager.GetString("ErrorSaveSF2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error Exporting WAV 的本地化字符串。
        /// </summary>
        internal static string ErrorSaveWAV {
            get {
                return ResourceManager.GetString("ErrorSaveWAV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This SDAT archive has no sequences. 的本地化字符串。
        /// </summary>
        internal static string ErrorSDATNoSequences {
            get {
                return ResourceManager.GetString("ErrorSDATNoSequences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;{0}&quot; is not an integer value. 的本地化字符串。
        /// </summary>
        internal static string ErrorValueParse {
            get {
                return ResourceManager.GetString("ErrorValueParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;{0}&quot; must be between {1} and {2}. 的本地化字符串。
        /// </summary>
        internal static string ErrorValueParseRanged {
            get {
                return ResourceManager.GetString("ErrorValueParseRanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GBA Files 的本地化字符串。
        /// </summary>
        internal static string FilterOpenGBA {
            get {
                return ResourceManager.GetString("FilterOpenGBA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SDAT Files 的本地化字符串。
        /// </summary>
        internal static string FilterOpenSDAT {
            get {
                return ResourceManager.GetString("FilterOpenSDAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DLS Files 的本地化字符串。
        /// </summary>
        internal static string FilterSaveDLS {
            get {
                return ResourceManager.GetString("FilterSaveDLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MIDI Files 的本地化字符串。
        /// </summary>
        internal static string FilterSaveMIDI {
            get {
                return ResourceManager.GetString("FilterSaveMIDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SF2 Files 的本地化字符串。
        /// </summary>
        internal static string FilterSaveSF2 {
            get {
                return ResourceManager.GetString("FilterSaveSF2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WAV Files 的本地化字符串。
        /// </summary>
        internal static string FilterSaveWAV {
            get {
                return ResourceManager.GetString("FilterSaveWAV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data 的本地化字符串。
        /// </summary>
        internal static string MenuData {
            get {
                return ResourceManager.GetString("MenuData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 End Current Playlist 的本地化字符串。
        /// </summary>
        internal static string MenuEndPlaylist {
            get {
                return ResourceManager.GetString("MenuEndPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export All WAV 的本地化字符串。
        /// </summary>
        internal static string MenuExportAllWAV {
            get {
                return ResourceManager.GetString("MenuExportAllWAV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File 的本地化字符串。
        /// </summary>
        internal static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open GBA ROM (AlphaDream) 的本地化字符串。
        /// </summary>
        internal static string MenuOpenAlphaDream {
            get {
                return ResourceManager.GetString("MenuOpenAlphaDream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open DSE Folder 的本地化字符串。
        /// </summary>
        internal static string MenuOpenDSE {
            get {
                return ResourceManager.GetString("MenuOpenDSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open GBA ROM (MP2K) 的本地化字符串。
        /// </summary>
        internal static string MenuOpenMP2K {
            get {
                return ResourceManager.GetString("MenuOpenMP2K", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open SDAT File 的本地化字符串。
        /// </summary>
        internal static string MenuOpenSDAT {
            get {
                return ResourceManager.GetString("MenuOpenSDAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Playlist 的本地化字符串。
        /// </summary>
        internal static string MenuPlaylist {
            get {
                return ResourceManager.GetString("MenuPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export VoiceTable as DLS 的本地化字符串。
        /// </summary>
        internal static string MenuSaveDLS {
            get {
                return ResourceManager.GetString("MenuSaveDLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export Song as MIDI 的本地化字符串。
        /// </summary>
        internal static string MenuSaveMIDI {
            get {
                return ResourceManager.GetString("MenuSaveMIDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export VoiceTable as SF2 的本地化字符串。
        /// </summary>
        internal static string MenuSaveSF2 {
            get {
                return ResourceManager.GetString("MenuSaveSF2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export Song as WAV 的本地化字符串。
        /// </summary>
        internal static string MenuSaveWAV {
            get {
                return ResourceManager.GetString("MenuSaveWAV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 C;C#;D;D#;E;F;F#;G;G#;A;A#;B 的本地化字符串。
        /// </summary>
        internal static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next Song 的本地化字符串。
        /// </summary>
        internal static string PlayerNextSong {
            get {
                return ResourceManager.GetString("PlayerNextSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Notes 的本地化字符串。
        /// </summary>
        internal static string PlayerNotes {
            get {
                return ResourceManager.GetString("PlayerNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pause 的本地化字符串。
        /// </summary>
        internal static string PlayerPause {
            get {
                return ResourceManager.GetString("PlayerPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Play 的本地化字符串。
        /// </summary>
        internal static string PlayerPlay {
            get {
                return ResourceManager.GetString("PlayerPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Position 的本地化字符串。
        /// </summary>
        internal static string PlayerPosition {
            get {
                return ResourceManager.GetString("PlayerPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Previous Song 的本地化字符串。
        /// </summary>
        internal static string PlayerPreviousSong {
            get {
                return ResourceManager.GetString("PlayerPreviousSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rest 的本地化字符串。
        /// </summary>
        internal static string PlayerRest {
            get {
                return ResourceManager.GetString("PlayerRest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop 的本地化字符串。
        /// </summary>
        internal static string PlayerStop {
            get {
                return ResourceManager.GetString("PlayerStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tempo 的本地化字符串。
        /// </summary>
        internal static string PlayerTempo {
            get {
                return ResourceManager.GetString("PlayerTempo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type 的本地化字符串。
        /// </summary>
        internal static string PlayerType {
            get {
                return ResourceManager.GetString("PlayerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unpause 的本地化字符串。
        /// </summary>
        internal static string PlayerUnpause {
            get {
                return ResourceManager.GetString("PlayerUnpause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Music 的本地化字符串。
        /// </summary>
        internal static string PlaylistMusic {
            get {
                return ResourceManager.GetString("PlaylistMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Would you like to play the following playlist?{0} 的本地化字符串。
        /// </summary>
        internal static string PlayPlaylistBody {
            get {
                return ResourceManager.GetString("PlayPlaylistBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VoiceTable saved to {0}. 的本地化字符串。
        /// </summary>
        internal static string SuccessSaveDLS {
            get {
                return ResourceManager.GetString("SuccessSaveDLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MIDI saved to {0}. 的本地化字符串。
        /// </summary>
        internal static string SuccessSaveMIDI {
            get {
                return ResourceManager.GetString("SuccessSaveMIDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VoiceTable saved to {0}. 的本地化字符串。
        /// </summary>
        internal static string SuccessSaveSF2 {
            get {
                return ResourceManager.GetString("SuccessSaveSF2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WAV saved to {0}. 的本地化字符串。
        /// </summary>
        internal static string SuccessSaveWAV {
            get {
                return ResourceManager.GetString("SuccessSaveWAV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Arguments 的本地化字符串。
        /// </summary>
        internal static string TrackViewerArguments {
            get {
                return ResourceManager.GetString("TrackViewerArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Event 的本地化字符串。
        /// </summary>
        internal static string TrackViewerEvent {
            get {
                return ResourceManager.GetString("TrackViewerEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Offset 的本地化字符串。
        /// </summary>
        internal static string TrackViewerOffset {
            get {
                return ResourceManager.GetString("TrackViewerOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ticks 的本地化字符串。
        /// </summary>
        internal static string TrackViewerTicks {
            get {
                return ResourceManager.GetString("TrackViewerTicks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Track Viewer 的本地化字符串。
        /// </summary>
        internal static string TrackViewerTitle {
            get {
                return ResourceManager.GetString("TrackViewerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Track {0} 的本地化字符串。
        /// </summary>
        internal static string TrackViewerTrackX {
            get {
                return ResourceManager.GetString("TrackViewerTrackX", resourceCulture);
            }
        }
    }
}
